[package]
name = "actix-cloud-codegen"
version = "0.1.0"
edition = "2021"

[features]
default = []
i18n = ["dep:rust-i18n-support"]

[dependencies]
quote = "1.0.36"
syn = "2.0.72"
proc-macro2 = "1.0.86"

rust-i18n-support = { version = "3.1.1", optional = true }

[lib]
proc-macro = true
