[package]
name = "actix-cloud"
version = "0.2.0"
edition = "2021"
authors = ["MXWXZ <matrixwxz@gmail.com>"]
description = "Actix Cloud is an all-in-one web framework based on Actix Web."
license = "MIT"
readme = "../README.md"
repository = "https://github.com/MXWXZ/actix-cloud"
keywords = ["http", "web", "framework", "async", "actix"]
categories = [
    "network-programming",
    "asynchronous",
    "web-programming::http-server",
    "web-programming::websocket",
]

[features]
default = ["logger"]
serde = ["dep:serde", "dep:serde_json", "dep:serde_with"]
memorydb = []
redis = ["dep:redis", "memorydb"]
rustls = ["actix-web/rustls-0_23", "dep:rustls", "dep:rustls-pemfile"]
logger = ["dep:tracing", "dep:tracing-subscriber", "dep:colored", "serde"]
i18n = ["actix-cloud-codegen/i18n", "dep:qstring"]
session = ["dep:actix-utils", "serde", "dep:rand", "memorydb"]
config = ["dep:config"]
config-json = ["config", "config/json"]
config-yaml = ["config", "config/yaml"]
config-toml = ["config", "config/toml"]
response = []
response-json = ["response", "serde"]
response-build = [
    "response",
    "dep:walkdir",
    "dep:yaml-rust2",
    "dep:quote",
    "dep:syn",
    "dep:prettyplease",
]
traceid = ["dep:tracing-actix-web"]

[dependencies]
actix-web = { version = "4.9.0", features = ["secure-cookies"] }
parking_lot = "0.12.3"
thiserror = "1.0.63"
tokio = { version = "1.39.2", features = ["full"] }
async-trait = "0.1.81"
chrono = "0.4.38"
futures = "0.3.30"
anyhow = "1.0.86"

actix-cloud-codegen = { version = "0.1.1", path = "../actix-cloud-codegen" }

# serde
serde = { version = "1.0.208", features = ["derive"], optional = true }
serde_json = { version = "1.0.125", optional = true }
serde_with = { version = "3.9.0", optional = true }

# logger
tracing = { version = "0.1.40", optional = true }
tracing-subscriber = { version = "0.3.18", features = [
    "json",
    "parking_lot",
], optional = true }
colored = { version = "2.1.0", optional = true }

# redis
redis = { version = "0.26.1", features = [
    "tokio-rustls-comp",
    "connection-manager",
], optional = true }

# rustls
rustls = { version = "0.23.12", optional = true }
rustls-pemfile = { version = "2.1.3", optional = true }

# session
actix-utils = { version = "3.0.1", optional = true }
rand = { version = "0.8.5", optional = true }

# config
config = { version = "0.14.0", optional = true }

# build
walkdir = { version = "2.5.0", optional = true }
yaml-rust2 = { version = "0.8.1", optional = true }
quote = { version = "1.0.36", optional = true }
syn = { version = "2.0.74", optional = true }
prettyplease = { version = "0.2.20", optional = true }

# i18n
qstring = { version = "0.7.2", optional = true }

# traceid
tracing-actix-web = { version = "0.7.11", optional = true }

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
